server:
  port: ${port:8881}

# xxl.job.admin.addresses
xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
      # xxl.job.executor.appname
    executor:
      appname: xxl-job-sharding-executor
      port: ${executor.port:9999}
      logpath: /Users/stone/logs/xxl-job