server:
  port: 9999
spring:
  application:
    name: es-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/headlines_article?useSSL=false
    username: root
    password: 86338633
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.stone.model.article.pojos
#自定义elasticsearch连接配置
elasticsearch:
  host: localhost
  port: 9200
